---
- name: Copy Configuration Nginx Default Setting
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default

- name: Restart Nginx
  service:
    name: nginx
    state: restarted