name: Github Action Workflow
run-name: Terraform Provisioning 

on: 
  push:
    branches: ["dev"]

permissions:
  id-token: write

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      

      - name: Terraform Apply 
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_CLIENT_ACCESS }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_CLIENT_ACCESS: ${{ secrets.TF_VAR_CLIENT_ACCESS }}
        run: |
          terraform init
          terraform plan 
          terraform apply --auto-approve
        working-directory: ./terraform